name: OSS-Fuzz
on: [pull_request]
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@cbb4b6b028c9ba2c2d545122da32fc9fd81eb628 # master 2026-03-15
      with:
        oss-fuzz-project-name: 'zlib'
        dry-run: false

    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@cbb4b6b028c9ba2c2d545122da32fc9fd81eb628 # master 2026-03-15
      with:
        oss-fuzz-project-name: 'zlib'
        fuzz-seconds: 300
        dry-run: false

    - name: Upload Crash
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      if: failure()
      with:
        name: artifacts
        path: ./out/artifacts
