name: OSS-Fuzz
on: [pull_request]
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@031b7912c013a3288588fa1583accbf30134e513  # master as of 2026-02-26; no tagged releases available
      with:
        oss-fuzz-project-name: 'zlib'
        dry-run: false

    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@031b7912c013a3288588fa1583accbf30134e513  # master as of 2026-02-26; no tagged releases available
      with:
        oss-fuzz-project-name: 'zlib'
        fuzz-seconds: 300
        dry-run: false

    - name: Upload Crash
      uses: actions/upload-artifact@v6
      if: failure()
      with:
        name: artifacts
        path: ./out/artifacts
