name: OSS-Fuzz
on: [pull_request]
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@9363767fc9731df14ea92d2b814e9201ac87bf5c # 2026-03-17
      with:
        oss-fuzz-project-name: 'zlib'
        dry-run: false

    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@9363767fc9731df14ea92d2b814e9201ac87bf5c # 2026-03-17
      with:
        oss-fuzz-project-name: 'zlib'
        fuzz-seconds: 300
        dry-run: false

    - name: Upload Crash
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      if: failure()
      with:
        name: artifacts
        path: ./out/artifacts
