name: anyVM-OSes

on: [push, pull_request]

jobs:

  dragonflybsd:
    runs-on: ubuntu-latest
    name: DragonflyBSD
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: DragonflyBSD
      uses: vmactions/dragonflybsd-vm@04601322b25fa8eb14f0394e46e1103084ea0199 # v1
      with:
        copyback: false
        prepare: |
          pkg install -y cmake gcc14 bzip2

        run: |
          cmake . -B build -DZLIB_BUILD_MINIZIP=ON -DMINIZIP_ENABLE_BZIP2=ON
          cmake --build build/
          ctest --test-dir build --output-on-failure

  freebsd:
    runs-on: ubuntu-latest
    name: FreeBSD - ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: aarch64
          - name: x86_64
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: FreeBSD - ${{ matrix.name }}
      uses: vmactions/freebsd-vm@c9f815bc7aa0d34c9fdd0619b034a32d6ca7b57e # v1
      with:
        arch: ${{ matrix.name }}
        copyback: false
        release: "15.0"
        prepare: |
          pkg install -y cmake gcc14 bzip2

        run: |
          cmake . -B build -DZLIB_BUILD_MINIZIP=ON -DMINIZIP_ENABLE_BZIP2=ON
          cmake --build build/
          ctest --test-dir build --output-on-failure -E .*summary

  netbsd:
    runs-on: ubuntu-latest
    name: NetBSD - ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: aarch64
          - name: x86_64
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: NetBSD - ${{ matrix.name }}
      uses: vmactions/netbsd-vm@e04aec09540429f9cebb0e7941f7cd0c0fc3b44f # v1
      with:
        copyback: false
        prepare: |
          export PATH="/usr/pkg/sbin:/usr/pkg/bin:$PATH"
          export PKG_PATH="https://cdn.NetBSD.org/pub/pkgsrc/packages"
          export PKG_PATH="$PKG_PATH/$(uname -s)/$(uname -m)/$(uname -r|cut -f '1 2' -d.)/All"
          /usr/sbin/pkg_add cmake
          /usr/sbin/pkg_add bzip2

        run: |
          cmake . -B build -DZLIB_BUILD_MINIZIP=ON -DMINIZIP_ENABLE_BZIP2=ON
          cmake --build build/
          ctest --test-dir build --output-on-failure

  omni-os:
    runs-on: ubuntu-latest
    name: OmniOS
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: OmniOS
      uses: vmactions/omnios-vm@8c95371c73e913746b40f808c9eab96fe278b6a7 # v1
      with:
        copyback: false
        prepare: |
          pkg install cmake gcc14 make bzip2

        run: |
          cmake . -B build -DZLIB_BUILD_MINIZIP=ON -DMINIZIP_ENABLE_BZIP2=ON
          cmake --build build/
          ctest --test-dir build --output-on-failure

  openbsd:
    runs-on: ubuntu-latest
    name: OpenBSD - ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: aarch64
          - name: x86_64
          - name: riscv64
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: OpenBSD - ${{ matrix.name }}
      uses: vmactions/openbsd-vm@9a8e4351a4a0dc6238e7c69276dcbf6c03bea576 # v1
      with:
        arch: ${{ matrix.name }}
        copyback: false
        prepare: |
          pkg_add cmake
          bzip2

        run: |
          cmake . -B build -DZLIB_BUILD_MINIZIP=ON -DMINIZIP_ENABLE_BZIP2=ON
          cmake --build build/
          ctest --test-dir build

#  openindiana:
#    runs-on: ubuntu-latest
#    name: OpenIndiana
#    steps:
#    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
#    - name: OpenIndiana
#      uses: vmactions/openindiana-vm@v0
#      with:
#        copyback: false
#        prepare: |
#          pkg install cmake gcc-14 make bzip2

#        run: |
#          cmake . -B build -DZLIB_BUILD_MINIZIP=ON -DMINIZIP_ENABLE_BZIP2=ON
#          cmake --build build/
#          ctest --test-dir build --output-on-failure

  solaris:
    runs-on: ubuntu-latest
    name: Solaris
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Solaris
      uses: vmactions/solaris-vm@69d382b4a775b25ea5955e6c1730e9d05047ca0d # v1
      with:
        copyback: false
        release: "11.4-gcc"
        prepare: |
          pkgutil -U
          pkgutil -y -i cmake bzip2

        run: |
          cmake . -B build -DZLIB_BUILD_MINIZIP=ON -DMINIZIP_ENABLE_BZIP2=ON
          cmake --build build/
          ctest --test-dir build --output-on-failure
